FROM oven/bun:1-alpine

WORKDIR /app
ENV NODE_ENV=development

RUN apk add --no-cache \
    build-base python3 python3-dev \
    vips-dev libpng-dev libjpeg-turbo-dev zlib-dev openssl-dev git

EXPOSE 3000

COPY .config/entrypoint.dev.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

CMD ["/usr/local/bin/entrypoint.sh"]
